---

all:
  vars:
    ansible_user: iacuser
    ansible_python_interpreter: '/usr/bin/python3.9'
    k8s_user: iacuser
    k8s_version: '1.28'
    k8s_cluster_name: 'ai-lab'
    crio_version: '1.28'
    os_stream: CentOS_9_Stream
    calico_version: 'v3.30.0'
    calico_images:
      - node
      - kube-controllers
      - cni
      - pod2daemon-flexvol
      - typha
      - csi
      - node-driver-registrar
    
    local_registry_host: 'registry.iac-lab.local'
    local_registry_port: '5000'
    local_registry_ip: '192.168.184.137'  # Ansible controller IP
    local_registry_name: 'local-registry'
    
    role_path: '../../roles'  # role path related to the playbooks 

    helm_repos:
      - name: bitnami 
        url: 'https://charts.bitnami.com/bitnami'

      - name: prometheus-community
        url: 'https://prometheus-community.github.io/helm-charts'

      - name: grafana
        url: 'https://grafana.github.io/helm-charts'
        
      - name: argo
        url: 'https://argoproj.github.io/argo-helm'
      
    helm_plugins:
      - name: helm-diff
        url: 'https://github.com/databus23/helm-diff'

    kubeconfig_path: '/home/{{ ansible_user }}/.kube/config'
    
  children:
    master:
      hosts:
        master-node:
          ansible_host: 192.168.184.143

    workers:
      hosts:
        worker-node:
          ansible_host: 192.168.184.138

    local_mirror:
      hosts:
        mirror-node:
     
    controller:
      hosts:
        localhost:
       
    # apps
    nginx:
      hosts:
        nginx_host:
          ansible_host: localhost
    
    mon_stack:
      hosts:
        mon_stack_host:
          ansible_host: localhost

    cleanup:
      hosts:
        cleanup_host:
          ansible_host: localhost

    argo_cd:
      hosts:
        argo_cd_host:
          ansible_host: localhost

  hosts:
    localhost:
      ansible_connection: local

    mirror-node:
      ansible_host: localhost  # Can later change to a remote IP
      ansible_connection: local  # Remove or change to ssh when remote