---

all:
  vars:
    ansible_user: iacuser
    k8s_user: iacuser
    k8s_version: '1.28'
    crio_version: '1.28'
    os_stream: CentOS_9_Stream
    calico_version: '3.30.0'
  
  children:
    master:
      hosts:
        192.168.184.135:
    workers:
      hosts:
        192.168.184.134:

