---

all:
  vars:
    ansible_user: iacuser
    ansible_python_interpreter: '/usr/bin/python3.9'
    k8s_user: iacuser
    k8s_version: '1.28'
    crio_version: '1.28'
    os_stream: CentOS_9_Stream
    calico_version: '3.30.0'

    helm_repos:
      - name: bitnami 
        url: 'https://charts.bitnami.com/bitnami'

      - name: prometheus-community
        url: 'https://prometheus-community.github.io/helm-charts'

      - name: grafana
        url: 'https://grafana.github.io/helm-charts'
        
      - name: argo
        url: 'https://argoproj.github.io/argo-helm'
      
    helm_plugins:
      - name: helm-diff
        url: 'https://github.com/databus23/helm-diff'

    kubeconfig_path: '/home/{{ ansible_user }}/.kube/config'
    
  children:
    master:
      hosts:
        192.168.184.134:
        # 192.168.184.138:
    workers:
      hosts:
        192.168.184.135:
        # 192.168.184.140:
    # apps
    nginx:
      hosts:
        nginx_host:
          ansible_host: localhost

    mon_stack:
      hosts:
        mon_stack_host:
          ansible_host: localhost

    cleanup:
      hosts:
        cleanup_host:
          ansible_host: localhost

    argo_cd:
      hosts:
        argo_cd_host:
          ansible_host: localhost