---

- name: Install NGINX via Helm using kubernetes.core.helm
  hosts: localhost
  connection: local
  gather_facts: no
  no_log: true
  vars:
    test_namespace: 'my-test-namespace'
  tasks:
    - name: Install nginx with Helm
      kubernetes.core.helm:
        name: my-nginx-nodeport
        chart_ref: bitnami/nginx
        release_namespace: "{{ test_namespace }}"
        create_namespace: true
        values:
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
        timeout: 600s
        kubeconfig: "{{ kubeconfig_path }}"
        update_repo_cache: true
        wait: true
      register: deploy_status
    
    - name: Print out chart deployment status
      ansible.builtin.debug:
        msg: "{{ deploy_status.status }}"

    - name: List Helm releases
      ansible.builtin.command: helm list --all-namespaces
      register: helm_list_output

    - name: Show Helm release list
      ansible.builtin.debug:
        msg: "{{ helm_list_output.stdout_lines }}"

    - name: Get pod info in the namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ test_namespace }}"
        kubeconfig: "{{ kubeconfig_path }}"
      register: nginx_pods
      no_log: false

    - name: Display pod names and status
      ansible.builtin.debug:
        msg: "{{ item.metadata.name }} - {{ item.status.phase }}"
      loop: "{{ nginx_pods.resources }}"
      no_log: false


