---
# handlers file for kubelet_dns

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: yes
