---
# tasks file for helm_chart
  
- name: Install/upgrade helm release
  kubernetes.core.helm:
    name: "{{ helm_release_name }}"
    chart_ref: "{{ helm_chart_ref }}"
    chart_version: "{{ helm_chart_version }}"
    release_namespace: "{{ k8s_namespace }}"
    create_namespace: true
    values: "{{ values }}"
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    update_repo_cache: true
    wait: true
    timeout: "{{ helm_chart_timeout }}"
    atomic: true
    force: true
  register: helm_result
  notify: Post Deployment Tests

- name: Debug Helm result
  ansible.builtin.debug:
    msg: "{{ helm_result.stdout }}"
