---

# ------------ Initialize cluster control plane on master ------------ #
- name: Initialize k8s control plane on master node and install Pod network Calico
  hosts: master
  gather_facts: false
  become: true
  roles:
    - roles/init_cluster

# ----------------------- Join worker nodes to master --------------------- # 
- name: Join worker nodes
  hosts: workers
  gather_facts: false
  become: true
  tasks:
    - name: Copy join script from Ansible controller to worker nodes
      ansible.builtin.copy:
        src: /tmp/k8s-join-command/kubeadm_join.sh
        dest: /tmp/kubeadm_join.sh
        mode: '0755'

    - name: Run kubeadm join
      ansible.builtin.command: sh /tmp/kubeadm_join.sh
      args:
        creates: /etc/kubernetes/kubelet.conf
      changed_when: false

# -------------------------------- Configure kubelet DNS on all nodes ------------------------------ # 
- name: Configure kubelet DNS on all nodes
  hosts: master, workers
  gather_facts: false
  become: true
  roles:
    - roles/kubelet_dns
  
# ----------------------- Install Calico CNI, apply CoreDNS patch on master node --------------------- #
- name: Install Calico CNI, apply CoreDNS patch on master node
  hosts: master
  gather_facts: false
  become: true
  roles:
    - roles/instl_calico
    - roles/patch_coredns

