---

- name: k8s Pre-requisites Playbook
  ansible.builtin.import_playbook: k8s_pre_requisites.yml

- name: K8s Cluster Bootstrap Playbook
  ansible.builtin.import_playbook: k8s_bootstrap_cluster.yml
