---
# tasks file for instl_calico

- name: Apply Calico CNI with Overlay Networking mode using tigera-operator.yaml manifest
  ansible.builtin.shell: >
    kubectl apply --server-side --force-conflicts -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/{{ item }}
  loop:
    - 'operator-crds.yaml'    # Custom Resource Definitions (CRDs)
    - 'tigera-operator.yaml'  # Tigera Calico Operator
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf  # for ansible_user to run kubectl command
  register: calico_apply_result
  failed_when: calico_apply_result.rc != 0
  changed_when: false

- name: Wait a few seconds for CRDs to register
  ansible.builtin.pause:
    seconds: 5
  
- name: Apply custom Calico installation manifest (disable BGP, enable encapsulation)
  ansible.builtin.copy:
    dest: /tmp/calico-installation.yaml
    content: |
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          bgp: Disabled
          ipPools:
          - blockSize: 26
            cidr: 192.168.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
  changed_when: false

- name: Apply Calico Installation
  ansible.builtin.shell: >
    kubectl apply --server-side --force-conflicts -f /tmp/calico-installation.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false
