- name: Post Deploy Checkings
  hosts: master
  gather_facts: no

  tasks:
    # ++++++++++++++++++++++++ check Pod ++++++++++++++++++++++++ #
    - name: Get pod info in the namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ k8s_namespace }}"
        kubeconfig: "{{ kubeconfig_path }}"
      register: pods_info
      
    - name: Display pod names and status
      ansible.builtin.debug:
        msg: "{{ item.metadata.name }} - {{ item.status.phase }}"
      loop: "{{ pods_info.resources }}"
