---
- name: Deploy kube-prometheus-stack
  hosts: mon_stack
  connection: local
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}" 
  
  roles:
    - ../../roles/mon_stack_crds
    - ../../roles/helm_chart