---

- name: Install Prometheus on RHEL 9 Master Node
  hosts: master
  gather_facts: false
  become: true

  vars:
    prometheus_dir: "/etc/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"

  tasks:
    - name: Create necessary directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        mode: '0755'
      loop:
        - "{{ prometheus_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Download proper version of Prometheus tarball
      ansible.builtin.get_url:
        url: "{{ 'https://github.com/prometheus/prometheus/releases/download/v' + prometheus_version +
              '/prometheus-' + prometheus_version+ '.linux-amd64.tar.gz' }}"
        dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Prometheus tarball
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/opt/"
        remote_src: true
        creates: "/opt/prometheus-{{ prometheus_version }}.linux-amd64"

    - name: Move binaries to /usr/local/bin/ directory
      ansible.builtin.copy:
        remote_src: true
        src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
      loop:
        - prometheus
        - promtool

    - name: Copy Prometheus config from /opt to {{ prometheus_dir }}
      ansible.builtin.copy:
        remote_src: yes
        src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
        dest: "{{ prometheus_dir }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        mode: '0644'

    - name: Create Prometheus systemd service under /etc/systemd/system
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_user }}
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file={{ prometheus_dir }}/prometheus.yml \
            --storage.tsdb.path={{ prometheus_data_dir }}
       
          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: started
