---

k8s_namespace: 'k8s-monitoring'
helm_release_name: 'kube-prometheus-stack'

# kube-prometheus-stack chart variables
helm_chart_ref: 'prometheus-community/kube-prometheus-stack'
helm_chart_version: '72.6.3'
helm_chart_timeout: 45m
required_crds:
  - alertmanagers.monitoring.coreos.com
  - alertmanagerconfigs.monitoring.coreos.com
  - podmonitors.monitoring.coreos.com
  - prometheuses.monitoring.coreos.com
  - prometheusrules.monitoring.coreos.com
  - servicemonitors.monitoring.coreos.com
  - thanosrulers.monitoring.coreos.com

# kube-prometheus-stack release values (dict)
values:
  prometheusOperator:   
    namespaceOverride: k8s-monitoring
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
    podDnsConfig:
      enabled: true
      nameservers:
        - 1.1.1.1
      options:
        - name: ndots
          value: "2"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    tolerations:  # temp
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

  kubeStateMetrics:
    namespaceOverride: k8s-monitoring
    podDnsConfig:
      enabled: true
      nameservers:
        - 1.1.1.1
      options:
        - name: ndots
          value: "2"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

  grafana:
    namespaceOverride: k8s-monitoring
    adminPassword: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35393965653237383864323362396462313935306330656236333635363330366634643735656462
          3835333865653936396130386333613133626631613431310a363966656137333935366166623430
          63363262346632616133323838363330613232386563393566366566633431613133303735356230
          3235356363626338330a333232373163336566383965666635346330343938626663383932616534
          3837
    service:
      type: NodePort
      nodePort: 30300
    podDnsConfig:
      enabled: true
      nameservers:
        - 1.1.1.1
      options:
        - name: ndots
          value: "2"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    persistence:
      enabled: false
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

  prometheus:
    namespaceOverride: k8s-monitoring
    service:
      type: NodePort
      nodePort: 30900
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: true
      podDnsConfig:
        enabled: true
        nameservers:
          - 1.1.1.1
        options:
          - name: ndots
            value: "2"
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      storageSpec: {}
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

  alertmanager:
    namespaceOverride: k8s-monitoring
    alertmanagerSpec:
      podDnsConfig:
        enabled: true
        nameservers:
          - 1.1.1.1
        options:
          - name: ndots
            value: "2"
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

  nodeExporter:
    namespaceOverride: k8s-monitoring
    hostNetwork: true
    podDnsConfig:
      enabled: true
      nameservers:
        - 1.1.1.1
      options:
        - name: ndots
          value: "2"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
